"""Portable SQLAlchemy schema for the legacy AlphaDatabase aggregate."""

from __future__ import annotations

from sqlalchemy import Column, Float, ForeignKey, Index, Integer, MetaData, String, Table, Text, UniqueConstraint
from sqlalchemy.engine import Engine

from alpha_operator_framework.infrastructure.sqlalchemy_migrations import migrate as migrate_research_runtime


metadata = MetaData()


def _text(name: str, *, key: bool = False, nullable: bool = True, default: str | None = None) -> Column:
    return Column(name, String(255) if key else Text, nullable=nullable, server_default=default)


def _id() -> Column:
    return Column("id", Integer, primary_key=True, autoincrement=True)


Table("trial_ledger", metadata, _id(), _text("trial_id", key=True, nullable=False), _text("expression", nullable=False), _text("family", key=True, nullable=False), _text("region", key=True, nullable=False), _text("universe", key=True, nullable=False), _text("metrics_json", nullable=False), _text("created_at", nullable=False), UniqueConstraint("trial_id"))
Table("alpha_expressions", metadata, _id(), _text("alpha_sha", key=True, nullable=False), _text("expression", nullable=False), _text("expression_origin", nullable=False, default=""), _text("settings", nullable=False), Column("batch_id", Integer), _text("fields", nullable=False, default="[]"), _text("status", key=True, nullable=False, default="pending"), _text("pruning_status", key=True, nullable=False, default="active"), _text("first_operator", key=True, nullable=False, default=""), _text("created_at", nullable=False), _text("updated_at", nullable=False), UniqueConstraint("alpha_sha"))
Table("round_candidates", metadata, _id(), _text("round_id", key=True, nullable=False), _text("candidate_id", key=True, nullable=False), _text("alpha_sha", key=True, nullable=False), _text("family", key=True, nullable=False), _text("template_id", key=True, nullable=False), _text("selection_status", key=True, nullable=False, default="generated"), _text("selection_reason"), _text("score_components_json"), _text("pruning_status", key=True, nullable=False, default="active"), _text("created_at", nullable=False), _text("updated_at", nullable=False), UniqueConstraint("round_id", "candidate_id"))
Table("alpha_details", metadata, _id(), _text("alpha_id", key=True, nullable=False), _text("alpha_sha", key=True, nullable=False, default=""), _text("expression", nullable=False), _text("region", key=True), _text("universe", key=True), Column("delay", Integer), Column("decay", Float), _text("neutralization", key=True), Column("truncation", Float), Column("sharpe", Float), Column("fitness", Float), Column("turnover", Float), Column("margin", Float), Column("pnl", Float), Column("returns", Float), Column("drawdown", Float), Column("long_count", Integer), Column("short_count", Integer), _text("grade", key=True), _text("stage_platform", key=True), _text("status_platform", key=True), _text("wf_stage", key=True, nullable=False, default="pending_validation"), _text("sc_result", key=True), Column("sc_value", Float), _text("pc_result", key=True), Column("pc_value", Float), _text("checks_json"), Column("ra_failed", Integer, server_default="0"), Column("ppa_failed", Integer, server_default="0"), _text("created_at", nullable=False), _text("updated_at", nullable=False), UniqueConstraint("alpha_id"))
Table("alpha_checks", metadata, _text("alpha_id", key=True, nullable=False, default=""), _text("check_name", key=True, nullable=False, default=""), _text("result", key=True), Column("limit", Float), Column("value", Float), _text("extra_json"), _text("created_at", nullable=False), _text("updated_at", nullable=False), UniqueConstraint("alpha_id", "check_name"))
Table("datafields", metadata, _text("field_id", key=True, nullable=False, default=""), _text("dataset_id", key=True, nullable=False, default=""), _text("dataset_name", nullable=False), _text("description", nullable=False), _text("type", key=True, nullable=False), _text("region", key=True, nullable=False), Column("delay", Integer, nullable=False), _text("universes_json", nullable=False), Column("coverage", Float), Column("date_coverage", Float), Column("user_count", Integer), Column("alpha_count", Integer), _text("category", key=True, nullable=False), _text("alpha_shas_json", nullable=False), _text("last_fetched_at"), _text("created_at", nullable=False), _text("updated_at", nullable=False), UniqueConstraint("field_id", "dataset_id", "region", "delay"))
Table("field_signal_stats", metadata, _id(), _text("field_id", key=True, nullable=False), _text("dataset_id", key=True, nullable=False), _text("region", key=True, nullable=False), _text("universe", key=True, nullable=False), Column("delay", Integer, nullable=False), Column("round", Integer, nullable=False), Column("trials", Integer, nullable=False), Column("signal_count", Integer, nullable=False), Column("hit_rate", Float, nullable=False), Column("avg_sharpe", Float, nullable=False), Column("max_sharpe", Float, nullable=False), Column("min_sharpe", Float, nullable=False), Column("avg_fitness", Float, nullable=False), _text("created_at", nullable=False), _text("updated_at", nullable=False), UniqueConstraint("field_id", "dataset_id", "region", "universe", "delay", "round"))
Table("pair_signal_stats", metadata, _id(), _text("pair_spec", key=True, nullable=False), _text("pair_kind", key=True, nullable=False), _text("region", key=True, nullable=False), _text("universe", key=True, nullable=False), Column("delay", Integer, nullable=False), Column("round", Integer, nullable=False), Column("trials", Integer, nullable=False), Column("signal_count", Integer, nullable=False), Column("hit_rate", Float, nullable=False), Column("avg_sharpe", Float, nullable=False), Column("max_sharpe", Float, nullable=False), Column("min_sharpe", Float, nullable=False), _text("created_at", nullable=False), _text("updated_at", nullable=False), UniqueConstraint("pair_spec", "region", "universe", "delay", "round"))
Table("operator_signal_stats", metadata, _id(), _text("operator", key=True, nullable=False), _text("region", key=True, nullable=False), _text("universe", key=True, nullable=False), Column("delay", Integer, nullable=False), Column("round", Integer, nullable=False), Column("trials", Integer, nullable=False), Column("signal_count", Integer, nullable=False), Column("hit_rate", Float, nullable=False), Column("avg_sharpe", Float, nullable=False), Column("max_sharpe", Float, nullable=False), Column("min_sharpe", Float, nullable=False), Column("avg_fitness", Float, nullable=False), _text("created_at", nullable=False), _text("updated_at", nullable=False), UniqueConstraint("operator", "region", "universe", "delay", "round"))
Table("template_prune_rules", metadata, _id(), _text("pattern", key=True, nullable=False), _text("pattern_type", key=True, nullable=False), _text("family", key=True, nullable=False), _text("reason", nullable=False), _text("source", key=True, nullable=False), Column("active", Integer, nullable=False), _text("created_at", nullable=False), _text("updated_at", nullable=False), UniqueConstraint("pattern", "pattern_type"))
Table("result_prune_rules", metadata, _id(), _text("scope_hash", key=True, nullable=False), _text("pattern", key=True, nullable=False), _text("pattern_type", key=True, nullable=False), _text("reason", nullable=False), _text("created_at", nullable=False), _text("updated_at", nullable=False), UniqueConstraint("scope_hash", "pattern", "pattern_type"))
Table("optimization_lineage", metadata, _id(), _text("scope_hash", key=True, nullable=False), _text("parent_alpha_sha", key=True, nullable=False), _text("child_alpha_sha", key=True, nullable=False), _text("stage", key=True, nullable=False), _text("created_at", nullable=False), _text("updated_at", nullable=False), UniqueConstraint("scope_hash", "parent_alpha_sha", "child_alpha_sha", "stage"))
Table("template_library", metadata, _id(), _text("name", key=True, nullable=False), *[_text(name, nullable=False) for name in ("title", "family", "template_type", "expression_template", "expression_origin", "field_types_json", "categories_json", "dataset_families_json", "placeholders_json", "group_slots_json", "description", "rationale", "example_expression", "settings_hint_json", "field_candidates_json", "operators_used_json", "source_json", "signal_constraints_json", "created_at", "updated_at")], Column("template_index", Integer, nullable=False), Column("fields_per_alpha", Integer, nullable=False), Column("slot_count", Integer, nullable=False), Column("parent_template_id", Integer), Column("active", Integer, nullable=False), UniqueConstraint("name"))
Table("simulation_batches", metadata, _id(), _text("round_id", key=True), _text("platform_batch_id", key=True), _text("platform_location"), _text("simulation_type", key=True, nullable=False), _text("status", key=True, nullable=False), _text("settings_json", nullable=False), Column("requested_count", Integer, nullable=False), Column("completed_count", Integer, nullable=False, server_default="0"), Column("failed_count", Integer, nullable=False, server_default="0"), _text("progress_json"), _text("result_json"), _text("error_message"), _text("submitted_at"), _text("last_polled_at"), _text("completed_at"), _text("created_at", nullable=False), _text("updated_at", nullable=False), UniqueConstraint("platform_batch_id"))
Table("simulation_results", metadata, _id(), Column("batch_id", Integer, ForeignKey("simulation_batches.id"), nullable=False), Column("sequence_no", Integer, nullable=False), _text("alpha_sha", key=True, nullable=False), _text("expression", nullable=False), _text("task_json", nullable=False), Column("decay", Float, nullable=False), _text("platform_child_url"), _text("alpha_id", key=True), _text("status", key=True, nullable=False), _text("result_json"), _text("error_message"), _text("completed_at"), _text("created_at", nullable=False), _text("updated_at", nullable=False), UniqueConstraint("batch_id", "sequence_no"))
Table("super_alpha_candidates", metadata, _id(), _text("candidate_sha", key=True, nullable=False), _text("component_ids_json", nullable=False), _text("selection_name", key=True, nullable=False), _text("selection", nullable=False), _text("combo_name", key=True, nullable=False), _text("combo", nullable=False), _text("settings_json", nullable=False), _text("status", key=True, nullable=False, default="prepared"), _text("alpha_id", key=True), _text("result_json"), _text("error_message"), _text("created_at", nullable=False), _text("updated_at", nullable=False), UniqueConstraint("candidate_sha"))
Table("alpha_optimization_queue", metadata, _id(), _text("alpha_id", key=True, nullable=False), _text("expression", nullable=False), Column("sharpe", Float), Column("fitness", Float), Column("turnover", Float), Column("margin", Float), _text("failed_checks"), Column("failed_ra_count", Integer), Column("failed_ppa_count", Integer), _text("optimization_hints"), _text("status", key=True), Column("priority", Integer), Column("retry_count", Integer), _text("created_at", nullable=False), _text("updated_at", nullable=False))
Table("alpha_submission_candidates", metadata, _id(), _text("alpha_id", key=True, nullable=False), _text("expression", nullable=False), Column("sharpe", Float), Column("fitness", Float), Column("turnover", Float), Column("margin", Float), Column("sc_value", Float), Column("pc_value", Float), Column("local_sc", Float), _text("local_sc_grade", key=True), _text("robustness_status", key=True), _text("robustness_notes"), Column("needs_optimization", Integer), Column("is_submitted", Integer), _text("submitted_at"), _text("pyramid_category", key=True), Column("pyramid_multiplier", Float), _text("created_at", nullable=False), _text("updated_at", nullable=False), UniqueConstraint("alpha_id"))
Table("backtest_dataset_records", metadata, _id(), _text("region", key=True, nullable=False), _text("universe", key=True, nullable=False), Column("delay", Integer, nullable=False), _text("dataset_id", key=True, nullable=False), _text("strategy", key=True, nullable=False), Column("expression_count", Integer, nullable=False), Column("backtest_count", Integer, nullable=False), _text("created_at", nullable=False), _text("updated_at", nullable=False), UniqueConstraint("region", "universe", "delay", "dataset_id", "strategy"))

Index("idx_detail_sharpe", metadata.tables["alpha_details"].c.sharpe)
Index("idx_sim_batch_status", metadata.tables["simulation_batches"].c.status)


def migrate_legacy_schema(engine: Engine) -> None:
    migrate_research_runtime(engine)
    metadata.create_all(engine)
